# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: George Ciesinski
title: Python Programmer
email: george.ciesin@gmail.com
website: https://GeorgeCiesinski.github.io

# Social links
twitter_username: GeorgeCiesinski
github_username:  GeorgeCiesinski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: george-ciesinski-5a8a134a
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/bio-photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is George and I am an IT professional. As well as providing L1 phone and email support, I also have experience making software. I have worked on numerous solo projects, as well as projects within a team.

  I am most skilled in: <mark>Python</mark> and <mark>Git</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming, some of my other interests are:
   - 3D Printing
   - Reading
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
